version: "3.8"

services:
  # Database
  linkinpurry-db:
    container_name: linkinpurry-db
    image: postgres:17
    env_file: .env
    ports:
      - "5436:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./src/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - linkinpurry-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}",
        ]

  # Development (with Xdebug & Volume binding for refreshing)
  linkinpurry-web-dev:
    container_name: linkinpurry-web-dev
    build:
      context: .
      target: development
    env_file: .env
    volumes:
      - ./:/var/www/
    ports:
      - "8080:80"
    depends_on:
      - linkinpurry-db
    networks:
      - linkinpurry-network

  # Production (without Xdebug & no Volume binding)
  linkinpurry-web-prod:
    container_name: linkinpurry-web-prod
    build:
      context: .
      target: production
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - linkinpurry-db
    networks:
      - linkinpurry-network

volumes:
  db-data:

networks:
  linkinpurry-network:
    driver: bridge
