version: "3.8"

services:
  # Development (with Xdebug & Volume binding for refreshing)
  web-dev:
    container_name: linkinpurry-web-dev
    build:
      context: .
      target: development
    env_file: .env
    volumes:
      - ./:/var/www/
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - linkinpurry-network

  # Production (without Xdebug & no Volume binding)
  web-prod:
    container_name: linkinpurry-web-prod
    build:
      context: .
      target: production
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - linkinpurry-network

  # Database
  db:
    container_name: linkinpurry-db
    image: postgres:17
    env_file: .env
    ports:
      - "5436:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./src/database/migrations:/docker-entrypoint-initdb.d

volumes:
  db-data:

networks:
  linkinpurry-network:
    driver: bridge
